### ISSUE TITLE
Cannot EVA

### ISSUE THREAD

**Issue by JackIt999** [KSP-RO/ROCapsules#36] opened 2020-07-24 00:28 UTC
I cannot EVA from any of the capsules, it says the hatch is obstructed (and it isnt). I tried this multiple times even without any other added parts.

**Comment by DJDC13** [comment] 2021-01-31 00:56
have you had any luck solving this @JackIt999 ? I am having the same issue

**Comment by Capkirk123** [comment] 2022-10-23 05:28
Cannot reproduce. Going to close this if there are no further comments

**Closed** 2023-07-05 23:24 UTC
