### ISSUE TITLE
Mercury capsule does not show up on map view

### ISSUE THREAD

**Issue by JenningsSVK** [KSP-RO/ROCapsules#142] opened 2023-05-13 15:00 UTC
Whenever a craft contains a mercury capsule then the craft will not show up on map view and map view gets focused on Earth by default (and on some occasions the map view starts to zoom out by itself indefinetly). Orbit, Ap, Pe, etc. Show up as normal, no craft icon though. Issue verified on a fresh RO install in sandbox (mod conflicts are therefore ruled out).

**Comment by NathanKell** [comment] 2023-05-30 06:02
Do you recall what mods you might have updated around then? Or was this your first RO/RP-1 install?

**Comment by JenningsSVK** [comment] 2023-05-30 06:51
It was a first install of RO/RP1 onto a fresh copy of KSP

Dňa ut 30. 5. 2023, 8:02 NathanKell ***@***.***> napísal(a):

**Comment by siimav** [comment] 2023-06-26 10:14
I've heard that his might be caused by KSPCF. https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/59

**Comment by NathanKell** [comment] 2023-07-23 02:21
Fixed in https://github.com/KSP-RO/ROCapsules/commit/f1f580d80e096f3ded0088f391e3d7160293adb1

**Closed** 2023-07-23 02:21 UTC
